### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/training/data/file'

### ISSUE THREAD

**Issue by dazaohehe** [iqiyi/FASPell#10]
“## 微调训练
  $ cd bert_modified
    $ python create_data.py -f /path/to/training/data/file
    $ python create_tf_record.py --input_file correct.txt --wrong_input_file wrong.txt --output_file tf_examples.tfrecord --vocab_file ../model/pre-trained/vocab.txt

执行 $ python create_data.py -f /path/to/training/data/file 时，报错FileNotFoundError: [Errno 2] No such file or directory: '/path/to/training/data/file'

**Comment by eugene-yh** [comment]
> “## 微调训练
> $ cd bert_modified
> $ python create_data.py -f /path/to/training/data/file
> $ python create_tf_record.py --input_file correct.txt --wrong_input_file wrong.txt --output_file tf_examples.tfrecord --vocab_file ../model/pre-trained/vocab.txt
> 
> 执行 $ python create_data.py -f /path/to/training/data/file 时，报错FileNotFoundError: [Errno 2] No such file or directory: '/path/to/training/data/file'

您好，'/path/to/training/data/file' 这个字符串是一个占位符，您应该将其修改成实际的训练数据的路径
