### ISSUE TITLE
What are the token level results of SIGHAN13, SIGHAN14

### ISSUE THREAD

**Issue by cklsoft** [iqiyi/FASPell#12]
Hi, 
    Thanks for your great job. I've read your paper but I doesn't find the token level results of SIGHAN13, SIGHAN14. Can you share the results, thanks.

**Comment by eugene-yh** [comment]
> Hi,
> Thanks for your great job. I've read your paper but I doesn't find the token level results of SIGHAN13, SIGHAN14. Can you share the results, thanks.

Hi, thanks for your interest in our research. As stated in the paper, previous state-of-the-art models were only tested using the sentence-level metrics. That is why we did not record the results with token-level metrics for a fair comparison, except for the one on the SIGHAN15 test set for README clarity.

**Comment by amelieyu** [comment]
> Hi,
> Thanks for your great job. I've read your paper but I doesn't find the token level results of SIGHAN13, SIGHAN14. Can you share the results, thanks.

could we share the sighan result if you want, my mail : yu_qimei@163.com
