### ISSUE TITLE
可以分享一下训练好的模型数据吗

### ISSUE THREAD

**Issue by cabbageNoob** [iqiyi/FASPell#14]
您好，感谢您们的工作，我想复现这个模型的结果，但在fine-tune掩码语言模型时就会因为内存不足而中断训练。请问可以分享一下训练好的模型数据吗？

**Comment by eugene-yh** [comment]
> ...，但在fine-tune掩码语言模型时就会因为内存不足而中断训练。

您好，建议在专用于训练的有较大内存或GPU的机器上训练

> ...请问可以分享一下训练好的模型数据吗？

您好，目前没有放出计划

**Comment by bestpredicts** [comment]
开源个代码 不敢放出模型权重？ 有人成功复现的嘛
