### ISSUE TITLE
请问correct.txt 和wrong.txt是什么格式？

### ISSUE THREAD

**Issue by highinsky** [iqiyi/FASPell#15]
请问correct.txt 和wrong.txt是什么格式？有工具生成吗
![image](https://user-images.githubusercontent.com/30213255/70037940-66d93000-15f2-11ea-8540-1cdf24c2469f.png)

**Comment by eugene-yh** [comment]
> 请问correct.txt 和wrong.txt是什么格式？有工具生成吗
您看的这个脚本就是生成这两个文件的

**Comment by eugene-yh** [comment]
> 请问correct.txt 和wrong.txt是什么格式？有工具生成吗

您看的这个脚本就是生成这两个文件的

**Comment by highinsky** [comment]
好的，谢谢，那是基于哪些文件或样本生成wrong和correct文件呢
