### ISSUE TITLE
交流

### ISSUE THREAD

**Issue by will-wiki** [iqiyi/FASPell#17]
您好，想问下有没有项目交流群呀，那个字符char_meta.txt文件处理还是有点问题

**Comment by shm007g** [comment]
ids.txt 没有细致的IDS序列，基础词如年、牛都没有拆分。

另外，2013-2015年的数据有一些有错误，我进行了少许修正。数据的location也有点微妙，需要写代码处理下，参考
[csc_data13to15.zip](https://github.com/iqiyi/FASPell/files/3982413/csc_data13to15.zip)

**Comment by will-wiki** [comment]
@shm007g 嗯嗯好的，谢谢您的回答。另外我想求证一件事情，我通读完代码和论文之后，发现这个模型是只能解决同音同形近音的纠错问题，像多字少字这种语法问题应该是没办法处理的吧

**Comment by shm007g** [comment]
@will-wiki 你可能没看readme，只解决spellcheck问题，可替代词的问题

**Comment by will-wiki** [comment]
嗯嗯好的，谢谢！
