### ISSUE TITLE
请问可以分享下 char_meta.txt  文件吗

### ISSUE THREAD

**Issue by loserdog-err** [iqiyi/FASPell#19]
感谢作者开源！
根据 issue
https://github.com/iqiyi/FASPell/issues/13
https://github.com/iqiyi/FASPell/issues/5
搞了两天，实在搞不出来 char_meta.txt 。想问下真的有人根据 issue 的回复搞出来了吗？
作者可否分享下这个文件呢？ 谢谢。

**Comment by wzc118** [comment]
同求

**Comment by viclanwu** [comment]
同试了，无法复现结果。
cjklib这个本身只能给出笔画，而没有结构信息。要么就是做了额外的字形图像比对，要么就是额外人工标注了简单字。

**Comment by BigWavelet** [comment]
同求

**Comment by nonva** [comment]
不开源char_meta.txt估计是担心开放了无法复现结果，尴尬啦

**Comment by 980202006** [comment]
同求

**Comment by hscspring** [comment]
看看是否有帮助：
[The-DataStructure-and-Algorithms/Recursion/chinese_char_feature at master · hscspring/The-DataStructure-and-Algorithms](https://github.com/hscspring/The-DataStructure-and-Algorithms/tree/master/Recursion/chinese_char_feature)
