### ISSUE TITLE
＠eugene-yh　用cjklib的getStrokeOrder将＇不＇字分解后得到的笔画在ｉｄs.txt中找不到对应的字符？

### ISSUE THREAD

**Issue by wenston2006** [iqiyi/FASPell#20]
import cjklib
from cjklib import characterlookup
cjk = characterlookup.CharacterLookup('T')

．．．
decomp = cjk.getStrokeOrder(ss[1].decode('utf-8'))

结果如下：　（这里ｓｓ[1]为＇不＇字，我的电脑上ｐython2.7无法显示汉字，都是以十六进制显示，）
ss[1].decode('utf-8')
u'\u4e0d'
decomp
[u'\u31d0', u'\u31d2', u'\u31d1', u'\u31d4']

最终结果为：
U+4E0D	不	㇐㇒㇑㇔

㇐㇒㇑㇔这几个字符在idx.txt找不到对应字符，请问应该如何处理？

**Comment by axelning** [comment]
感觉这种字符就没必要去ids里去找了吧，直接拆完的字符串做编辑距离运算就好了
