### ISSUE TITLE
部分字没有字形

### ISSUE THREAD

**Issue by SolinTao** [iqiyi/FASPell#21]
感谢作者的贡献。但是有部分字，在ids和makemeahanzi中都无法找到字形表示，例如“牛”。麻烦问下是如何得到的呢？另外，还没有仔细研读论文，只有几千条数据集效果好吗？如果加入大量没有错别字的训练集，对模型有影响吗？

**Comment by axelning** [comment]
+1，比如禾，水这种都没有继续分解的数据了，那如果没有对数据做增补的情况下，出现禾VS水的需要比较相似度的情况下，相似度会有缺失。
我也想知道这部分是怎么考虑和解决的呢？
