### ISSUE TITLE
提供的训练数据，unihan的拼音数据， ids数据都是繁体中文，没有简体中文

### ISSUE THREAD

**Issue by BigWavelet** [iqiyi/FASPell#26]
提供的训练数据，unihan的拼音数据， ids数据都是繁体中文，没有简体中文。
请问训练出的模型能较好地应用在简体中文上么？
回复为盼， 感谢

**Comment by eugene-yh** [comment]
> 提供的训练数据，unihan的拼音数据， ids数据都是繁体中文，没有简体中文。
> 请问训练出的模型能较好地应用在简体中文上么？
> 回复为盼， 感谢

您好，unihan和ids包含繁体中文，简体中文以及其他所有CJK语言在unicode中编码的汉字。
SIGHAN13-15是繁体中文，因为这是公开的benchmark数据集。

另外，请注意，除OCR数据外，其它数据集均不是我们提供。请勿将版权归属弄错。

模型可以应用在任何中文文本上，不限简体繁体。
