### ISSUE TITLE
数据对齐问题

### ISSUE THREAD

**Issue by liqinc** [iqiyi/FASPell#28]
您好，这种训练方法可用于原句与改正句未对齐的情况吗，例如：原句是“有着举足轻的作用”，改正句是“有着举足轻重的作用”

**Comment by eugene-yh** [comment]
> 您好，这种训练方法可用于原句与改正句未对齐的情况吗，例如：原句是“有着举足轻的作用”，改正句是“有着举足轻重的作用”

您好，如README和论文所述，目前中文拼写纠错只纠错替换错误。不过我们正在开发可以修改漏字多字的错误的模型，请持续关注。

**Comment by Veyronl** [comment]
您好,关于多字少字的模型,预计几月份会分享呢@eugene-yh
