### ISSUE TITLE
CSD 部分 candidates 是不是只要存一次，我理解的对吗

### ISSUE THREAD

**Issue by huitang** [iqiyi/FASPell#34]
top_difference=True, sim_type='shape', rank=0  #就是这一次存起来  记做A
top_difference=True, sim_type='shape', rank=1 #用第一次的
top_difference=True, sim_type='shape', rank=2#用第一次的
        ...        ,       ...       ,   ...
top_difference=True, sim_type='sound', rank=0#用第一次的
top_difference=True, sim_type='sound', rank=1#用第一次的
top_difference=True, sim_type='sound', rank=2#用第一次的
        ...        ,       ...       ,   ...
top_difference=False, sim_type='shape', rank=0#用第一次的
top_difference=False, sim_type='shape', rank=1#用第一次的
top_difference=False, sim_type='shape', rank=2#用第一次的
        ...        ,       ...       ,   ...
top_difference=False, sim_type='sound', rank=0
top_difference=False, sim_type='sound', rank=1
top_difference=False, sim_type='sound', rank=2

**Comment by shicript** [comment]
bert预测的结果都是一样的，所以只存一次就可以了

**Comment by moyaojunshi** [comment]
CSD怎么训练？readme中关于CSD的没有看懂，更不知道top_difference从何而来
