### ISSUE TITLE
如何绘制confidence-similariy graph

### ISSUE THREAD

**Issue by XuJ** [iqiyi/FASPell#7]
你好，请问一下如何绘制论文中figure3第②和第③张的confidence-similariy graph？有相关的代码可以参考吗？谢谢。

**Comment by eugene-yh** [comment]
> 你好，请问一下如何绘制论文中figure3第②和第③张的confidence-similariy graph？有相关的代码可以参考吗？谢谢。

您好，在README的CSD训练部分详细描述了散点图的产生方法以及确定曲线后如何更新到faspell.py中。散点图相关代码主要在plot.py中。

**Comment by XuJ** [comment]
> > 你好，请问一下如何绘制论文中figure3第②和第③张的confidence-similariy graph？有相关的代码可以参考吗？谢谢。
> 
> 您好，在README的CSD训练部分详细描述了散点图的产生方法以及确定曲线后如何更新到faspell.py中。散点图相关代码主要在plot.py中。

谢谢回复。可能我表达得有些问题，散点图的产生方法和绘制您已经在readme和代码里解释得很清楚了，但是请问图中threshold那条曲线是如何确定的呢，faspell.py的Curves类别里只有全过滤和不过滤以及一个两条切线的例子，并没有能够复现论文中figure3第②和第③张的threshold曲线的方法。谢谢。

**Comment by eugene-yh** [comment]
> > > 你好，请问一下如何绘制论文中figure3第②和第③张的confidence-similariy graph？有相关的代码可以参考吗？谢谢。
> > 
> > 
> > 您好，在README的CSD训练部分详细描述了散点图的产生方法以及确定曲线后如何更新到faspell.py中。散点图相关代码主要在plot.py中。
> 
> 谢谢回复。可能我表达得有些问题，散点图的产生方法和绘制您已经在readme和代码里解释得很清楚了，但是请问图中threshold那条曲线是如何确定的呢，faspell.py的Curves类别里只有全过滤和不过滤以及一个两条切线的例子，并没有能够复现论文中figure3第②和第③张的threshold曲线的方法。谢谢。

确定曲线，如论文所述，需要手动进行。figure3第②和第③张的threshold曲线是理想情况。实际实验中，我们采取若干条切线来近似。具体的线条，可以通过在训练集上多次试验得出：曲线如果偏高，则试验精确率（字符级别，后同）不变召回率会下降，而如果曲线偏低，精确率会下降而召回率不变，所以寻找到这两者之间的平衡点即可。
