### ISSUE TITLE
汉字字形表示的问题

### ISSUE THREAD

**Issue by t-kong** [iqiyi/FASPell#8]
请问，如何操作才能找出比如人 的 ids -->⿰丿㇏  ?  
在cjkvi-ids/ids.txt 中只有 U+4EBA  人  人 ，怎样才能继续拆解呢？是否有额外的字典？  谢谢

**Comment by eugene-yh** [comment]
> 请问，如何操作才能找出比如人 的 ids -->⿰丿㇏ ?
> 在cjkvi-ids/ids.txt 中只有 U+4EBA 人 人 ，怎样才能继续拆解呢？是否有额外的字典？ 谢谢

请参考 https://github.com/iqiyi/FASPell/issues/5#issuecomment-552668982
